// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BTLNhom8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230521083044_Create_Table_Monhoc")]
    partial class Create_Table_Monhoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BTLNhom8.Models.Monhoc", b =>
                {
                    b.Property<string>("Ma_mon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ten_mon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ma_mon");

                    b.ToTable("Monhoc");
                });
#pragma warning restore 612, 618
        }
    }
}
